### ISSUE TITLE
Add mock for fetching data

### ISSUE THREAD

**Issue by vutran** [vutran/dext-github-plugin#6]
Create a [manual mock](https://facebook.github.io/jest/docs/manual-mocks.html) for `got` and create fake API response data.

**Comment by ChaudhariPrasad** [comment]
Hi Vutran,

Would like to take this task.
Could you give some head start on what exactly what i have to do for this.
FYI.. I will be working on windows machine so what steps i need to carry out.

Thanks,
Prasad

**Comment by vutran** [comment]
@ChaudhariPrasad Thanks for the interest. You will need some general knowledge of JavaScript, Node, and some knowledge of how testing/mocking works.

Please see below for some information on how to get started.

### Setup local environment:
1. Clone the git repository
2. Run `npm install` to install local packages
3. Run `npm test` to run current tests

### Begin writing new mocks/tests

We're using [`jest`](https://github.com/facebook/jest) as our choice of testing framework.

Mocks should be created in a `__mocks__` directory. To create a mock for [`got`](https://github.com/sindresorhus/got), you'll need to create a new file: `__mocks__/got.js`.

In this file, you'll have to overwrite the original implementation of the `got` module to allow return fake data so we can skip network requests (making it predictable).

Here's an example of a mock for the Node `fs` module: `fs.link` and `fs.unlink`:

```
// __mocks__/fs.js
const fs = jest.genMockFromModule('fs');

// mocks fs.link
fs.link = (src, dest, callback) => {
  // here, we're not doing anything and just call the callback
  callback.call(null);
};

// mocks fs.unlink
fs.unlink = (dest, callback) => {
  // here, we're not doing anything and just call the callback
  callback.call(null);
};

module.exports = fs;
```

In general, you'll need to mock [`got(url, [options])`](https://github.com/sindresorhus/got#goturl-options) and have it return a Promise for a `response` with a `body` property.

The `response.body` have to conform to the structure that is represented when making a real request to the GitHub API endpoint. In our mock function, we're practically overriding it to allow our `got()` to return our fake data.

See the quick example below:

```
const got = () => new Promise(resolve => resolve({
  // fill in the body with fake data that
  // represent the data structure from the GitHub API.
  body: { .... },
});
```

For re-usability, we would want to create a method to allow us to set fake data any time we want.

```
let mockData = null;

// here, we're creating a new function called __setFakeData() which sets the mockData variable
got.__setFakeData = (data) => {
  mockData = data;
};

// then in our mock `got()` function, we can set the mockData as the body
new Promise(resolve => {
  resolve({
    body: mockData,
  });
});
```

You would then need to update the existing [specs](https://github.com/vutran/dext-github-plugin/blob/master/__tests__/index.js) with your fake data.

```
require('got').__setFakeData(....); // set some fake data first

// then, simply write your test assertions...
expect(await got('fake_url')).toEqual(....);
```

Hope this helps. I've included more links for references:
- [Jest - Manual mocks](https://facebook.github.io/jest/docs/manual-mocks.html)
- [Jest manual mock example](https://github.com/facebook/jest/tree/master/examples/manual_mocks/__mocks__)
- [GitHub API - Search endpoint](https://developer.github.com/v3/search/#search-repositories)
- [got](https://github.com/sindresorhus/got)

**Comment by ChaudhariPrasad** [comment]
Thanks @vutran for sharing the steps.

Will surely give it a shot.

Thanks,
Prasad
